### ISSUE TITLE
download the dataset

### ISSUE THREAD

**Issue by Qiuvijay** [SohamBera16/foodetecto-An-AI-based-Food-category-detection-app-using-Streamlit-and-Heroku-Cloud#1]
Dear SohamBera16,

I found that I cannot register an account on [www.kaggle.com](http://www.kaggle.com/) while trying to download the dataset you provided, and I also can't log in using Google Mail. I attempted to contact the website's support team, but the feedback function on the site is also experiencing issues. Could you please provide an alternative way to download the dataset? Thank you very much.

Here is my email: qiuvijay@gmail.com

**Comment by SohamBera16** [comment]
Dear @Qiuvijay,
It seems like the Kaggle website register functionality is having some issues. Did you try registering with an alternative email address than the one with which you were having the issue? I tried the "Register with Google" option and for me it was pretty smooth.

Another way will be to get the dataset from the Kaggle API:
1. Set up your Kaggle API keys you can go through this link: kaggle.com/docs/api#authentication
2. pip install kaggle (on the terminal)
3. In the bash terminal, run this command: kaggle datasets download msarmi9/food101tiny

**Or, you could also do this:**
pip install kagglehub (on the terminal)
import kagglehub
path = kagglehub.dataset_download("msarmi9/food101tiny")
print("Path to dataset files:", path)

If none of these work, let me know and I will send you the zipped file of the dataset via email.

**Comment by Qiuvijay** [comment]
I appreciate your help; the problem has been resolved.
